# Generated by Django 5.0.6 on 2024-06-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='filial',
            field=models.CharField(max_length=100),
        ),
    ]
